### ISSUE TITLE
Does the GitHub pack support GitHub Enterprise?

### ISSUE THREAD

**Issue by kevinSuttle** [StackStorm/st2contrib#439]
Seems like the default is github.com. Wondering if a custom URL and auth method are supported, or could be. Thanks.

https://github.com/StackStorm/st2contrib/tree/master/packs/github

**Comment by emedvedev** [comment]
I think it wouldn't be hard to implement support. You'll need to move `base_url` to config, and make the python action read from it instead of hardcoding (https://github.com/StackStorm/st2contrib/blob/master/packs/github/actions/lib/base.py#L11), and then the only thing left would be to pass `base_url` to github constructor here: https://github.com/StackStorm/st2contrib/blob/master/packs/github/actions/lib/base.py#L19

If you run into trouble, we'll be glad to help! We would certainly appreciate a PR allowing GitHub Enterprise support.

**Comment by emedvedev** [comment]
You can read tests at PyGithub to learn how an Enterprise connection is implemented, like this one: https://github.com/PyGithub/PyGithub/blob/0e0b74a5d8caf0574b3bb4df6b85e61ba65c7376/github/tests/Issue80.py#L33

**Comment by kevinSuttle** [comment]
@emedvedev thanks. I'm new to Python, but I think I've got it. However, running `make all` throws an error here:

```bash
==================== packs-resource-register ====================

. virtualenv/bin/activate; if [ ! "/Users/kevinSuttle/Code/st2contrib/packs/github" ]; then echo No packs have changed, skipping run...; fi; for pack in /Users/kevinSuttle/Code/st2contrib/packs/github; do if [ -n "$pack" ]; then scripts/register-pack-resources.sh $pack || exit 1 ; fi; done
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/v6/cffs_4b125dfkbg0rh24f3nm0000gn/T/pip-build-dx6oU0/pyinotify/
Registering content from pack github
Traceback (most recent call last):
  File "/tmp/st2/st2common/bin/st2-register-content", line 19, in <module>
    import st2common.content.bootstrap as content_loader
  File "/tmp/st2/st2common/st2common/content/bootstrap.py", line 19, in <module>
    from oslo_config import cfg
ImportError: No module named oslo_config
Registering resources for pack github failed
make: *** [.packs-resource-register] Error 1
```

**Comment by kevinSuttle** [comment]
Opened a PR so someone can (in)validate.

**Comment by emedvedev** [comment]
Perfect, I'll review shortly. The `make all` error is likely due to a different version of `oslo` on your box. They changed `oslo.config` to `oslo_config` a while ago (or the other way around, I don't really remember). Our tests pass for your PR. :)
